name: Download artifacts from first job and display content in second job
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  write-job:
    name: Write to file and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: check-out from SCM
        uses: actions/checkout@v4
      - name: Write to file
        run: | 
          echo "Hello World" >> appFile.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appFile
          path: appFile.txt

  
  download-job: 
    runs-on: ubuntu-latest
    #needs: write-job
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v5
      with:
        name: appFile
    - name: Display file content
      run: |
        cat appFile.txt

